import imp
from random import Random


GOLDEN_RATIO = 1.61803398875
DEFAULT_SCREEN_WIDTH  = 400
DEFAULT_SCREEN_HEIGHT = int( DEFAULT_SCREEN_WIDTH * GOLDEN_RATIO )

CANVAS_HEIGHT = 350
CANVAS_WIDTH = DEFAULT_SCREEN_WIDTH -10
CANVAS_MAX_POINTS = 30000000

CALCULATOR_RANDOM_AMPLITUDE = 5
CALCULATOR_GRAVETYWELL = 0.5
CALCULATOR_STUBBORN = 0.000001
CALCULATOR_DELAY = 0.01

########################### THREAD VARIABLES ###########################
THREAD_COMMAND_EXIT = 1
THREAD_COMMAND_PAUSE = 2
THREAD_COMMAND_START = 3

THREAD_ID_GUIMAINLOOP = 1
THREAD_ID_MAIN = 2
